### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ralfHielscher** [mtex-toolbox/mtex#25]
I will keep the list updated with the further deveopment of MTEX. You may add any wishes you have.

- [ ] more slip transmission parameters
- [x] better support for hex grid - mtex-toolbox/mtex#282
- [ ] interpolation of scattered EBSD maps
- [ ] recrystalization
- [ ] image registration - low 
- [x] a class representing spherical functions, to be returned by ODF/calcPDF, tensors, axisDistributions, etc. - see https://github.com/felixbartel/mtex/tree/feature/sphFun
- [x] separate classes for different types of tensors, e.g. compliance, stiffness, ...
- [x] pole figure tensor - more information required
- [x] simultaneous rotation of figures 
- [x] misorientation axis / angle plot (specimen + crystal reference frame)
- [x] labels for color bars
- [x] implement a class representing fibres
- [x] nearest neighbor volume computation - requires still documentation :cactus: 
- [x] special class for Miller plots - which show ipdf like data cursor in opossite to sphericalPlot
- [x] Miller/symmetrise and orientation/symmetrise should return only unique elements on request

### Documentation
- [x] use https://mmistakes.github.io/minimal-mistakes/
- [ ] example of recrystallisation

### Import / Export
- [x] import hfd5 files
- [ ] EBSD import wizard plots map + pole figures, clicking the plot button in the import wizard on the crystal symmetry page should plot the current phase
- [x] export to VPSC orientation + grain shape ellipse
- [x] improve import of ctf files
- [x] improve import of osc files: symmetry + reference frame, ask Karsten for different files
